name: "Common Steps"
runs:
  using: "composite"
  steps:
  - name: Install build dependencies
    # Install dependencies for building packages on pre-release Pythons
    # jaraco/skeleton#161
    if: matrix.python == '3.14' && matrix.platform == 'ubuntu-latest'
    run: |
      sudo apt update
      sudo apt install -y libxml2-dev libxslt-dev
    shell: bash
  - name: Enable unprivileged ping sockets
    # actions/runner-images#11614
    if: matrix.platform == 'ubuntu-latest'
    shell: bash
    run: |
      echo 'net.ipv4.ping_group_range = 0 2147483647' | sudo tee -a /etc/sysctl.conf
      sudo sysctl -p
  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: ${{ matrix.python }}
      allow-prereleases: true
  - name: Install tox
    run: python -m pip install tox
    shell: bash
  - name: Run
    run: tox
    shell: bash
