name: tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: [3.6, 3.8, 3.9]
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Run tests
        run: python -c "import socket, pprint; pprint.pprint(socket.getaddrinfo('jaraco.com', None)); assert any(':' in item[4][0] for item in socket.getaddrinfo('jaraco.com', None))"
